language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean
  - ./gradlew check
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: # only send an email if build fails
    on_success: never
    on_failure: always

